server:
  port: 20037
spring:
  datasource:
    druid:
      max-active: 50
      min-idle: 10
      initial-size: 1
      filters: mergeStat
      max-wait: 10000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: true
      test-on-return: false
      time-between-eviction-runs-millis: 18800
      min-evictable-idle-time-millis: 150000
      time-between-log-stats-millis: 300000
    dynamic:
      primary: test
      datasource:
        test:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3310/test?zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=UTF-8&characterSetResults=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
