// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_basic.proto

package com.example.demo.protobuf.proto;

public final class BasicProto {
  private BasicProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_basic_RequestBasic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_basic_RequestBasic_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_basic_ResponseBasic_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_basic_ResponseBasic_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021proto_basic.proto\022\013proto.basic\"U\n\014Requ" +
      "estBasic\022\014\n\004time\030\001 \001(\003\022\023\n\013client_info\030\002 " +
      "\001(\t\022\020\n\010time_out\030\003 \001(\003\022\020\n\010platform\030\004 \001(\005\"" +
      "8\n\rResponseBasic\022\014\n\004code\030\001 \002(\005\022\014\n\004time\030\002" +
      " \001(\003\022\013\n\003msg\030\003 \001(\tB/\n\037com.example.demo.pr" +
      "otobuf.protoB\nBasicProtoP\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_basic_RequestBasic_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_basic_RequestBasic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_basic_RequestBasic_descriptor,
        new java.lang.String[] { "Time", "ClientInfo", "TimeOut", "Platform", });
    internal_static_proto_basic_ResponseBasic_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_basic_ResponseBasic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_basic_ResponseBasic_descriptor,
        new java.lang.String[] { "Code", "Time", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
