// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_basic.proto

package com.example.demo.protobuf.proto;

public interface RequestBasicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.basic.RequestBasic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional int64 time = 1;</code>
   */
  boolean hasTime();
  /**
   * <code>optional int64 time = 1;</code>
   */
  long getTime();

  /**
   * <code>optional string client_info = 2;</code>
   */
  boolean hasClientInfo();
  /**
   * <code>optional string client_info = 2;</code>
   */
  java.lang.String getClientInfo();
  /**
   * <code>optional string client_info = 2;</code>
   */
  com.google.protobuf.ByteString
      getClientInfoBytes();

  /**
   * <pre>
   * 超时时间，非时间戳 单位秒
   * </pre>
   *
   * <code>optional int64 time_out = 3;</code>
   */
  boolean hasTimeOut();
  /**
   * <pre>
   * 超时时间，非时间戳 单位秒
   * </pre>
   *
   * <code>optional int64 time_out = 3;</code>
   */
  long getTimeOut();

  /**
   * <pre>
   *平台   1 PC, 2 App(ios), 3 App(android), 4 WX(ios),5 WX(android), 6 黄金(ios), 7黄金(android) ,8 H5 (android), 9：H5 IOS, 99 系统代扣, 100 其他
   * </pre>
   *
   * <code>optional int32 platform = 4;</code>
   */
  boolean hasPlatform();
  /**
   * <pre>
   *平台   1 PC, 2 App(ios), 3 App(android), 4 WX(ios),5 WX(android), 6 黄金(ios), 7黄金(android) ,8 H5 (android), 9：H5 IOS, 99 系统代扣, 100 其他
   * </pre>
   *
   * <code>optional int32 platform = 4;</code>
   */
  int getPlatform();
}
