// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_basic.proto

package com.example.demo.protobuf.proto;

/**
 * Protobuf type {@code proto.basic.RequestBasic}
 */
public  final class RequestBasic extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:proto.basic.RequestBasic)
    RequestBasicOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RequestBasic.newBuilder() to construct.
  private RequestBasic(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RequestBasic() {
    time_ = 0L;
    clientInfo_ = "";
    timeOut_ = 0L;
    platform_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RequestBasic(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            time_ = input.readInt64();
            break;
          }
          case 18: {
            com.google.protobuf.ByteString bs = input.readBytes();
            bitField0_ |= 0x00000002;
            clientInfo_ = bs;
            break;
          }
          case 24: {
            bitField0_ |= 0x00000004;
            timeOut_ = input.readInt64();
            break;
          }
          case 32: {
            bitField0_ |= 0x00000008;
            platform_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.demo.protobuf.proto.BasicProto.internal_static_proto_basic_RequestBasic_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.demo.protobuf.proto.BasicProto.internal_static_proto_basic_RequestBasic_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.demo.protobuf.proto.RequestBasic.class, com.example.demo.protobuf.proto.RequestBasic.Builder.class);
  }

  private int bitField0_;
  public static final int TIME_FIELD_NUMBER = 1;
  private long time_;
  /**
   * <code>optional int64 time = 1;</code>
   */
  public boolean hasTime() {
    return ((bitField0_ & 0x00000001) == 0x00000001);
  }
  /**
   * <code>optional int64 time = 1;</code>
   */
  public long getTime() {
    return time_;
  }

  public static final int CLIENT_INFO_FIELD_NUMBER = 2;
  private volatile java.lang.Object clientInfo_;
  /**
   * <code>optional string client_info = 2;</code>
   */
  public boolean hasClientInfo() {
    return ((bitField0_ & 0x00000002) == 0x00000002);
  }
  /**
   * <code>optional string client_info = 2;</code>
   */
  public java.lang.String getClientInfo() {
    java.lang.Object ref = clientInfo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      if (bs.isValidUtf8()) {
        clientInfo_ = s;
      }
      return s;
    }
  }
  /**
   * <code>optional string client_info = 2;</code>
   */
  public com.google.protobuf.ByteString
      getClientInfoBytes() {
    java.lang.Object ref = clientInfo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      clientInfo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIME_OUT_FIELD_NUMBER = 3;
  private long timeOut_;
  /**
   * <pre>
   * 超时时间，非时间戳 单位秒
   * </pre>
   *
   * <code>optional int64 time_out = 3;</code>
   */
  public boolean hasTimeOut() {
    return ((bitField0_ & 0x00000004) == 0x00000004);
  }
  /**
   * <pre>
   * 超时时间，非时间戳 单位秒
   * </pre>
   *
   * <code>optional int64 time_out = 3;</code>
   */
  public long getTimeOut() {
    return timeOut_;
  }

  public static final int PLATFORM_FIELD_NUMBER = 4;
  private int platform_;
  /**
   * <pre>
   *平台   1 PC, 2 App(ios), 3 App(android), 4 WX(ios),5 WX(android), 6 黄金(ios), 7黄金(android) ,8 H5 (android), 9：H5 IOS, 99 系统代扣, 100 其他
   * </pre>
   *
   * <code>optional int32 platform = 4;</code>
   */
  public boolean hasPlatform() {
    return ((bitField0_ & 0x00000008) == 0x00000008);
  }
  /**
   * <pre>
   *平台   1 PC, 2 App(ios), 3 App(android), 4 WX(ios),5 WX(android), 6 黄金(ios), 7黄金(android) ,8 H5 (android), 9：H5 IOS, 99 系统代扣, 100 其他
   * </pre>
   *
   * <code>optional int32 platform = 4;</code>
   */
  public int getPlatform() {
    return platform_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      output.writeInt64(1, time_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientInfo_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      output.writeInt64(3, timeOut_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      output.writeInt32(4, platform_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) == 0x00000001)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, time_);
    }
    if (((bitField0_ & 0x00000002) == 0x00000002)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientInfo_);
    }
    if (((bitField0_ & 0x00000004) == 0x00000004)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timeOut_);
    }
    if (((bitField0_ & 0x00000008) == 0x00000008)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, platform_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.demo.protobuf.proto.RequestBasic)) {
      return super.equals(obj);
    }
    com.example.demo.protobuf.proto.RequestBasic other = (com.example.demo.protobuf.proto.RequestBasic) obj;

    boolean result = true;
    result = result && (hasTime() == other.hasTime());
    if (hasTime()) {
      result = result && (getTime()
          == other.getTime());
    }
    result = result && (hasClientInfo() == other.hasClientInfo());
    if (hasClientInfo()) {
      result = result && getClientInfo()
          .equals(other.getClientInfo());
    }
    result = result && (hasTimeOut() == other.hasTimeOut());
    if (hasTimeOut()) {
      result = result && (getTimeOut()
          == other.getTimeOut());
    }
    result = result && (hasPlatform() == other.hasPlatform());
    if (hasPlatform()) {
      result = result && (getPlatform()
          == other.getPlatform());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTime()) {
      hash = (37 * hash) + TIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTime());
    }
    if (hasClientInfo()) {
      hash = (37 * hash) + CLIENT_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getClientInfo().hashCode();
    }
    if (hasTimeOut()) {
      hash = (37 * hash) + TIME_OUT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeOut());
    }
    if (hasPlatform()) {
      hash = (37 * hash) + PLATFORM_FIELD_NUMBER;
      hash = (53 * hash) + getPlatform();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.demo.protobuf.proto.RequestBasic parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protobuf.proto.RequestBasic parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protobuf.proto.RequestBasic parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protobuf.proto.RequestBasic parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protobuf.proto.RequestBasic parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.demo.protobuf.proto.RequestBasic parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.demo.protobuf.proto.RequestBasic parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.protobuf.proto.RequestBasic parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.protobuf.proto.RequestBasic parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.demo.protobuf.proto.RequestBasic parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.demo.protobuf.proto.RequestBasic parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.demo.protobuf.proto.RequestBasic parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.demo.protobuf.proto.RequestBasic prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code proto.basic.RequestBasic}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:proto.basic.RequestBasic)
      com.example.demo.protobuf.proto.RequestBasicOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.demo.protobuf.proto.BasicProto.internal_static_proto_basic_RequestBasic_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.demo.protobuf.proto.BasicProto.internal_static_proto_basic_RequestBasic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.demo.protobuf.proto.RequestBasic.class, com.example.demo.protobuf.proto.RequestBasic.Builder.class);
    }

    // Construct using com.example.demo.protobuf.proto.RequestBasic.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      time_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      clientInfo_ = "";
      bitField0_ = (bitField0_ & ~0x00000002);
      timeOut_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000004);
      platform_ = 0;
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.demo.protobuf.proto.BasicProto.internal_static_proto_basic_RequestBasic_descriptor;
    }

    @java.lang.Override
    public com.example.demo.protobuf.proto.RequestBasic getDefaultInstanceForType() {
      return com.example.demo.protobuf.proto.RequestBasic.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.demo.protobuf.proto.RequestBasic build() {
      com.example.demo.protobuf.proto.RequestBasic result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.demo.protobuf.proto.RequestBasic buildPartial() {
      com.example.demo.protobuf.proto.RequestBasic result = new com.example.demo.protobuf.proto.RequestBasic(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
        to_bitField0_ |= 0x00000001;
      }
      result.time_ = time_;
      if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
        to_bitField0_ |= 0x00000002;
      }
      result.clientInfo_ = clientInfo_;
      if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
        to_bitField0_ |= 0x00000004;
      }
      result.timeOut_ = timeOut_;
      if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
        to_bitField0_ |= 0x00000008;
      }
      result.platform_ = platform_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.demo.protobuf.proto.RequestBasic) {
        return mergeFrom((com.example.demo.protobuf.proto.RequestBasic)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.demo.protobuf.proto.RequestBasic other) {
      if (other == com.example.demo.protobuf.proto.RequestBasic.getDefaultInstance()) return this;
      if (other.hasTime()) {
        setTime(other.getTime());
      }
      if (other.hasClientInfo()) {
        bitField0_ |= 0x00000002;
        clientInfo_ = other.clientInfo_;
        onChanged();
      }
      if (other.hasTimeOut()) {
        setTimeOut(other.getTimeOut());
      }
      if (other.hasPlatform()) {
        setPlatform(other.getPlatform());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.demo.protobuf.proto.RequestBasic parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.demo.protobuf.proto.RequestBasic) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long time_ ;
    /**
     * <code>optional int64 time = 1;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }
    /**
     * <code>optional int64 time = 1;</code>
     */
    public Builder setTime(long value) {
      bitField0_ |= 0x00000001;
      time_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional int64 time = 1;</code>
     */
    public Builder clearTime() {
      bitField0_ = (bitField0_ & ~0x00000001);
      time_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object clientInfo_ = "";
    /**
     * <code>optional string client_info = 2;</code>
     */
    public boolean hasClientInfo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string client_info = 2;</code>
     */
    public java.lang.String getClientInfo() {
      java.lang.Object ref = clientInfo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          clientInfo_ = s;
        }
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>optional string client_info = 2;</code>
     */
    public com.google.protobuf.ByteString
        getClientInfoBytes() {
      java.lang.Object ref = clientInfo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>optional string client_info = 2;</code>
     */
    public Builder setClientInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      clientInfo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional string client_info = 2;</code>
     */
    public Builder clearClientInfo() {
      bitField0_ = (bitField0_ & ~0x00000002);
      clientInfo_ = getDefaultInstance().getClientInfo();
      onChanged();
      return this;
    }
    /**
     * <code>optional string client_info = 2;</code>
     */
    public Builder setClientInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      clientInfo_ = value;
      onChanged();
      return this;
    }

    private long timeOut_ ;
    /**
     * <pre>
     * 超时时间，非时间戳 单位秒
     * </pre>
     *
     * <code>optional int64 time_out = 3;</code>
     */
    public boolean hasTimeOut() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * 超时时间，非时间戳 单位秒
     * </pre>
     *
     * <code>optional int64 time_out = 3;</code>
     */
    public long getTimeOut() {
      return timeOut_;
    }
    /**
     * <pre>
     * 超时时间，非时间戳 单位秒
     * </pre>
     *
     * <code>optional int64 time_out = 3;</code>
     */
    public Builder setTimeOut(long value) {
      bitField0_ |= 0x00000004;
      timeOut_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 超时时间，非时间戳 单位秒
     * </pre>
     *
     * <code>optional int64 time_out = 3;</code>
     */
    public Builder clearTimeOut() {
      bitField0_ = (bitField0_ & ~0x00000004);
      timeOut_ = 0L;
      onChanged();
      return this;
    }

    private int platform_ ;
    /**
     * <pre>
     *平台   1 PC, 2 App(ios), 3 App(android), 4 WX(ios),5 WX(android), 6 黄金(ios), 7黄金(android) ,8 H5 (android), 9：H5 IOS, 99 系统代扣, 100 其他
     * </pre>
     *
     * <code>optional int32 platform = 4;</code>
     */
    public boolean hasPlatform() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <pre>
     *平台   1 PC, 2 App(ios), 3 App(android), 4 WX(ios),5 WX(android), 6 黄金(ios), 7黄金(android) ,8 H5 (android), 9：H5 IOS, 99 系统代扣, 100 其他
     * </pre>
     *
     * <code>optional int32 platform = 4;</code>
     */
    public int getPlatform() {
      return platform_;
    }
    /**
     * <pre>
     *平台   1 PC, 2 App(ios), 3 App(android), 4 WX(ios),5 WX(android), 6 黄金(ios), 7黄金(android) ,8 H5 (android), 9：H5 IOS, 99 系统代扣, 100 其他
     * </pre>
     *
     * <code>optional int32 platform = 4;</code>
     */
    public Builder setPlatform(int value) {
      bitField0_ |= 0x00000008;
      platform_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     *平台   1 PC, 2 App(ios), 3 App(android), 4 WX(ios),5 WX(android), 6 黄金(ios), 7黄金(android) ,8 H5 (android), 9：H5 IOS, 99 系统代扣, 100 其他
     * </pre>
     *
     * <code>optional int32 platform = 4;</code>
     */
    public Builder clearPlatform() {
      bitField0_ = (bitField0_ & ~0x00000008);
      platform_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:proto.basic.RequestBasic)
  }

  // @@protoc_insertion_point(class_scope:proto.basic.RequestBasic)
  private static final com.example.demo.protobuf.proto.RequestBasic DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.demo.protobuf.proto.RequestBasic();
  }

  public static com.example.demo.protobuf.proto.RequestBasic getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<RequestBasic>
      PARSER = new com.google.protobuf.AbstractParser<RequestBasic>() {
    @java.lang.Override
    public RequestBasic parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RequestBasic(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RequestBasic> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RequestBasic> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.demo.protobuf.proto.RequestBasic getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

