// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto_basic.proto

package com.example.demo.protobuf.proto;

public interface ResponseBasicOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.basic.ResponseBasic)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int32 code = 1;</code>
   */
  boolean hasCode();
  /**
   * <code>required int32 code = 1;</code>
   */
  int getCode();

  /**
   * <code>optional int64 time = 2;</code>
   */
  boolean hasTime();
  /**
   * <code>optional int64 time = 2;</code>
   */
  long getTime();

  /**
   * <code>optional string msg = 3;</code>
   */
  boolean hasMsg();
  /**
   * <code>optional string msg = 3;</code>
   */
  java.lang.String getMsg();
  /**
   * <code>optional string msg = 3;</code>
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
