rocketmq:
  name-server:  192.168.83.1:9876
  producer:
    group: demo_producer_group
    send-message-timeout: 300000
    compress-message-body-threshold: 4096
    max-message-size: 4194304
    retry-next-server: true
    retry-times-when-send-async-failed: 0
    retry-times-when-send-failed: 2

